name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify the Terraform version you need

    - name: Install dependencies
      run: terraform init
      working-directory: 'gcp'
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: 'gcp'
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Plan Terraform deployment
      run: |
        terraform plan -out=tfplan -var-file="gcp/terraform.tfvars"
      working-directory: 'gcp'
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Apply Terraform deployment
      run: |
        terraform apply -auto-approve tfplan -var-file="gcp/terraform.tfvars" 
      working-directory: 'gcp'
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
